sample_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      user: db_user
      password: db_password
      port: 5432
      dbname: db_sample_dbt
      schema: public
